### ISSUE TITLE
MakeUrl is deprecated

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs/http-server#55]
## Package version

5.7.1

## Node.js and npm version

14.15.5 and 7.23.0

## Sample Code (to reproduce the issue)

Use a `redirect().toRoute('YourController')` in any application to print this message in the console
```sh
(node:30252) You are using legacy the API of the "Route.makeUrl". We recommend reading the docs and use the latest API: DeprecationWarning
```

This is created in [this file](https://github.com/adonisjs/http-server/blob/d17e0cb0c085dcdec61b17d4d03d678f552c9d36/src/Redirect/index.ts#L135) and reading the doc, the [new url builder must be used](https://docs.adonisjs.com/guides/routing#url-builder)

**Comment by thetutlage** [comment]
Can you please create a test for the same? I have tested it here https://github.com/adonisjs/http-server/blob/v5.7.2/test/redirect.spec.ts#L197 and no warning is printed

**Comment by Barbapapazes** [comment]
I will provide this asap !

**Comment by Barbapapazes** [comment]
Weird, I don't have this on a slim application, will investigate more!

**Comment by Barbapapazes** [comment]
Here the full warning

```sh
 node --trace-warnings .\server.js
[1648142868222] INFO (team/1372 on Esteban-PC): started server on 0.0.0.0:3333
(node:1372) You are using legacy the API of the "Route.makeUrl". We recommend reading the docs and use the latest API: DeprecationWarning
    at C:\Users\esoub\Projects-Dev\insamee-app\team\build\node_modules\@adonisjs\http-server\build\src\helpers.js:150:17
    at onIntersect (C:\Users\esoub\Projects-Dev\insamee-app\team\build\node_modules\@adonisjs\http-server\build\src\helpers.js:129:9)
    at normalizeMakeUrlOptions (C:\Users\esoub\Projects-Dev\insamee-app\team\build\node_modules\@adonisjs\http-server\build\src\helpers.js:149:5)
    at Router.makeUrl (C:\Users\esoub\Projects-Dev\insamee-app\team\build\node_modules\@adonisjs\http-server\build\src\Router\index.js:323:73)
    at Object.route (C:\Users\esoub\Projects-Dev\insamee-app\team\build\node_modules\@adonisjs\view\build\providers\ViewProvider.js:26:26)
    at eval (eval at wrapToFunction (C:\Users\esoub\Projects-Dev\insamee-app\team\build\node_modules\edge.js\build\src\Template\index.js:60:20), <anonymous>:900:33)
    at Template.asyncEach (C:\Users\esoub\Projects-Dev\insamee-app\team\build\node_modules\edge.js\build\src\utils\index.js:95:19)
    at template (eval at wrapToFunction (C:\Users\esoub\Projects-Dev\insamee-app\team\build\node_modules\edge.js\build\src\Template\index.js:60:20), <anonymous>:894:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at template (eval at wrapToFunction (C:\Users\esoub\Projects-Dev\insamee-app\team\build\node_modules\edge.js\build\src\Template\index.js:60:20), <anonymous>:37:8)
```

**Comment by Barbapapazes** [comment]
I found it, here the code I use

```edge
 @each(item in routesTeam)
    <li>
      <a href="{{ route(item.name, { qs: item.filters(auth.user?.profile) }) }}" class="flex flex-row items-center space-x-1 {{item.color}}">
        <div class="w-7">
          <img src="{{ asset(`assets/images/${item.asset}`) }}" alt="Logo de la plateforme {{ item.title }}" width="500" height="500" loading="lazy" class="h-6 w-auto">
        </div>
        <span>{{ item.title }}</span>
      </a>
    </li>
  @end
```

**Comment by Barbapapazes** [comment]
okk, I found it

**Comment by Barbapapazes** [comment]
So, `route` in edge is the issue because I write this (the qs is the second)
```edge
<a
  action="{{
    route('RedirectsController.index', {
      qs: {
        _method: 'PUT'
      }
    })
  }}"
>
  redirect
</a>
```

instead of this (the qs is the third parameters)
```edge
<a
  action="{{
    route('RedirectsController.index', { id: 1 }, {
      qs: {
        _method: 'PUT'
      }
    })
  }}"
>
  redirect
</a>

```

**Comment by Barbapapazes** [comment]
So, you can find [the repo here](https://github.com/Barbapapazes/makeUrl-reproduction) @thetutlage 

and the issue in this file
https://github.com/Barbapapazes/makeUrl-reproduction/blob/master/resources/views/home.edge

**Comment by Barbapapazes** [comment]
But maybe, I'm wrong in the code I write, so I think there is no issue.
